### ISSUE TITLE
Personas

### ISSUE THREAD

**Issue by suzalflueck** [bcgov/citz-dst-capstone-2021#17]
#### Persona Groups Identified:
- Submitter _Skylar to do_
- Financial Analyst _Samara to do_
- Executive
- Data Analyst
- Tool Admin

**Comment by suzalflueck** [comment]
Investigate tool that Robert linked

**Comment by SungHwan-Park** [comment]
https://app.theydo.io/login?path=%2Fgovofbc%2Fworkspace

**Comment by SungHwan-Park** [comment]
### Who reports?

(Investment Portfolio Office) of each ministry.

# Personas

## Drafter

Someone in IPO

**Actions**

- **_Create_** a new report.
- Revise the report based on conversations with project manager and feedbacks from director and executive director.

## Project manager/lead

**Actions**

- **_Register_** a new project.
- Review the reports.

## Director

**Actions**

- Review the reports, mostly focussing on issues and those reports that are not overall GREEN.
- _**Submit**_ a report to DIO

## Financial lead

**Actions**

- Ensure budgets, spends, etc. are up-to-date for that period
- _**Fill in financial details**_ not normally tracked by the PM, like Sitting in Ministry and JV’d to OCIO.

## Executive director

**Actions**

- Review
- _**Approve**_(Sign)

## DIO

- **_Receive_** submitted reports

## [Actions vs Roles](https://miro.com/app/board/o9J_lG4EXvQ=/?moveToWidget=3074457358961924574&cot=14)
