### ISSUE TITLE
Report Form: WS4-b Status Summary

### ISSUE THREAD

**Issue by suzalflueck** [bcgov/citz-dst-capstone-2021#214]
- [x] Comments are mandatory if status is not green
- [x] Comments mandatory if trend is down _Should they provide context as to why a situation has improved?_

**Comment by SungHwan-Park** [comment]
- disable step button when the project info is not confirmed
- add `getLastReport` API by adding `last` query param
- refactor App component to AppRouter and Home components
- apply Material UI ThemeProvider
  - change primary.main color to bcblue(#036)
- fix status type conversion in data model validation
- remove `@material-ui/styles` -> use `@material-ui/core/styles`
- query project by `cpsIdentifier` or `id`
