### ISSUE TITLE
Schematics for Current Reporting Process

### ISSUE THREAD

**Issue by suzalflueck** [bcgov/citz-dst-capstone-2021#24]
Develop information flow diagram(s) that describes the current report submission process

**Comment by suzalflueck** [comment]
- basic information flow diagram
- possible personas
Note: non technical person should understand

will be shared with stakeholder finance team

**Comment by SungHwan-Park** [comment]
### [Current Reporting Process](https://miro.com/app/board/o9J_lG4EXvQ=/?moveToWidget=3074457358790969201&cot=14)



### Who reports?

IPO(Investment Portfolio Office) of each ministry.

### Drafter

Person who enters a report into the system. Someone in IPO

### Project managers/leads

Each report is reviewed and revised based on conversations with the PM.  -> it means the project manager do not enter initial data.

### Director

- Review the reports, mostly focussing on issues and those reports that are not overall GREEN.
- Submit a report to DIO

### Financial lead

- Ensure budgets, spends, etc. are up-to-date for that period
- Fill in details not normally tracked by the PM, like Sitting in Ministry and JV’d to OCIO.

### Executive director

- Act on behalf of CIO
- Review and Approve(Sign)
- (We don’t review individual submissions with our ED as we normally discuss any issues using a spreadsheet summary)


**Answer from David Bayne**

> Quarterly reports are submitted by project managers/leads to our team which is the Investment Portfolio Office under our IT division for the Natural Resource Ministries. Each report is reviewed and revised based on conversations with the PM. Since we have more than a dozen capital funded projects at one time, we first meet with our Director to review the reports, mostly focussing on issues and those reports that are not overall GREEN.
In addition, we meet with our financial lead to ensure budgets, spends, etc. are up-to-date for that period, and fill in details not normally tracked by the PM, like Sitting in Ministry and JV’d to OCIO.
Once that review is complete, then it will get reviewed by our Exec Director (who is acting on behalf of the NRM CIO) and who can approve them individually. We don’t review individual submissions with our ED as we normally discuss any issues using a spreadsheet summary.
At this point, we revise based on any feedback, and the review is complete. All of the reports (and any other supporting documents) are attached to an email and sent by our Director to the DIO prior to the deadline.

**Comment by SungHwan-Park** [comment]
I am not sure who actually creates and revises the report.

**Comment by suzalflueck** [comment]
I can move schematics from Brainstorm Miro to either a cleaner board or export them to PDF. Do we want to do either of these options?
