### ISSUE TITLE
Git Upkeep & Hygiene

### ISSUE THREAD

**Issue by suzalflueck** [bcgov/citz-dst-capstone-2021#33]
- Branches should be kept to a minimum
- Automate pipeline for branch cleanup (jenkins perhaps?)

**Comment by SungHwan-Park** [comment]
@poornima-sivanand 
Can you set up the repo so that a branch would be deleted when it is merged?
It seems we don't have permission for that.

**Comment by poornima-sivanand** [comment]
Done
