### ISSUE TITLE
OCP Learning - Create capstone service account

### ISSUE THREAD

**Issue by suzalflueck** [bcgov/citz-dst-capstone-2021#39]
**1. create gmail called:** citz-dst-capstone-serviceaccount
**2. create GitHub with associated gmail**

GitHub account requires multi-factor authentication

**Comment by SpookySkylark** [comment]
Gmail:
citz.dst.capstone.service@gmail.com

GitHub:
citz-dst-capstone-service

Message me for log in codes.
