### ISSUE TITLE
Reduce Build Time

### ISSUE THREAD

**Issue by suzalflueck** [bcgov/citz-dst-capstone-2021#66]
Total build time has been reduced from 54m to 35m.

**Comment by SungHwan-Park** [comment]
### Server build-time

about 10 minutes


```
oc process -f ./openshift/server/bc.yaml -p VERSION=1.0 -p SUFFIX=beta -p GIT_BRANCH=main | oc apply -f -
```

| Time | Task | Duration |
| - | - | - |
| 18:30 | start | 0 |
| 22:00 | getting image | 3:30 |
| 22:30 | generating docker file | 2:30 |
| 26:00 | Installing npm dependencies | 3:30 |
| 26:40 | build | 0:40 |
| 28:00 | prune dev dependencies and cache | 1:20 |
| 28:30 | commit image | 0:30 |

### Client build-time

about 34 minutes

```
oc process -f ./openshift/client/bc.yaml -p VERSION=1.0 -p SUFFIX=beta -p GIT_BRANCH=main | oc apply -f -

```
| Completion Time | Task | Duration |
| - | - | - |
| 42:42 | start | 0 |
| 49:00 | getting image | 6:18 |
| 02:40 | Installing npm dependencies | 13:40 |
| 3:20 | postinstall | 0:40 |
| 8:34 | build | 5:14 |
| 12:00 | prune dev deps | 3:26 |
| 12:40 | cleaning | 0:40 |
| 16:50 | commit image | 4:10 |
| 17:15 | push image | 0:25 |

**Comment by SungHwan-Park** [comment]
### Notes of Pipeline-cli best practises training session

Monday, May 31

- How to hook approve on github and pass to jenkins
  ask Poornima

- To prevent permission errors related to Jenkins
  bind admin role to Jenkins serviceaccount

- For HA, increase replicas in dc.yaml

- To use docker.io, set secret
  see [Docker & Artifactory implementation details](https://github.com/BCDevOps/OpenShift4-Migration/issues/51)

- To run unit/e-e tests on Jenkins
  see [bcgov/mds Jenkinsfile](https://github.com/bcgov/mds/blob/develop/Jenkinsfile)

- To reduce image-build-time
  set imageOptimizationPolicy to skiplayers under buildconfig/sourcestrategy

- To upgrade nodejs image
  try [ubi8/nodejs-14](https://catalog.redhat.com/software/containers/rhel8/nodejs-14/5ed76a59d70cc50e69c2f891)

**Comment by SungHwan-Park** [comment]
npm version in ubi/nodejs-14 image is also 6 and lockfileVersion is 1.

The best way to match npm version is using npm version 6

```
npm i -g npm@6.14.13
```
