### ISSUE TITLE
Front End Prototype (First Iteration)

### ISSUE THREAD

**Issue by suzalflueck** [bcgov/citz-dst-capstone-2021#78]
Create first iteration of SPA front end prototype
- Have NPM, React, and Formik installed
- Front end routing set up
- Should be hosted on OpenShift

Decide with team what exactly is best for scope of first prototype.
- [ ] Basic sign in/authentication
- [ ] Can submit basic form. _Do not overcomplicate, start with "Hello World" and build from there_
- [ ] Surface data submitted via form to application. _Connect to basic DB prototype?_

**Comment by CITZ-rwk** [comment]
well done team!
